### ISSUE TITLE
It is possible to use Hypernova with Preact?

### ISSUE THREAD

**Issue by tanraya** [airbnb/hypernova-react#24]
Hello.
I'm trying to use Hypernova with Preact, but getting following error:

```
Development Warning! The 0 component failed to render with Hypernova. Error stack:
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c85468c5-7b6f-4c14-9ba0-b42dccaed6bc/commercial/cscp/app/javascript/components/application/login.js:1:1)
    at Module._compile (module.js:571:32)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getComponent (/mnt/c85468c5-7b6f-4c14-9ba0-b42dccaed6bc/commercial/cscp/config/hypernova.server.js:7:12)
    at BatchManager.render (/mnt/c85468c5-7b6f-4c14-9ba0-b42dccaed6bc/commercial/cscp/node_modules/hypernova/lib/utils/BatchManager.js:170:22)
    at /mnt/c85468c5-7b6f-4c14-9ba0-b42dccaed6bc/commercial/cscp/node_modules/hypernova/lib/utils/lifecycle.js:170:22
```

I'm also trying to add this lines to my webpack config but it didn't give any result:

```js
    alias: {
      'react': 'preact-compat',
      'react-dom': 'preact-compat'
    }
```
Any clues on that?

**Comment by goatslacker** [comment]
Are you running the aliased webpack output in node?

**Comment by BobbyAdamson** [comment]
Hey @tanraya did you ever find a solution for this? I am working on integrating Preact with a Rails app and hypernova seems like a decent fit if I can get it preact compatable.

**Comment by ljharb** [comment]
@BobbyAdamson see 
https://github.com/airbnb/hypernova-react/issues/24#issuecomment-333663595, you may need to make your own `hypernova-preact`.

**Comment by marconi1992** [comment]
@tanraya you can take a look at this bindings for Preact. https://www.npmjs.com/package/hypernova-preact

**Comment by ljharb** [comment]
Closing, since the package now exists.
